# Generated by Django 3.2.13 on 2022-04-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('AM', 'Assistant Manager'), ('M', 'Manager'), ('SM', 'Senior Manager')], max_length=20)),
                ('python', models.IntegerField(default=0)),
                ('r', models.IntegerField(default=0)),
                ('java', models.IntegerField(default=0)),
                ('powerbi', models.IntegerField(default=0)),
                ('datetime_created', models.DateTimeField(blank=True)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Resource_Fact',
        ),
    ]
