# Generated by Django 3.2.13 on 2022-04-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20220417_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='datetime_created',
        ),
    ]
